# Generated by Django 5.0.1 on 2024-06-24 16:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                ("email", models.EmailField(max_length=250, null=True)),
                (
                    "age",
                    models.IntegerField(
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(120),
                            django.core.validators.MinValueValidator(12),
                        ],
                    ),
                ),
                ("info", models.TextField(blank=True, null=True)),
                (
                    "username",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
